export const ABOUT_WORDS = [
  "RVCC",
  "IS",
  "[img1]",
  "DEDICATED",
  "TO",
  "EXCELLENCE",
  "THROUGH",
  "INTEGRITY",
  "AND",
  "ETHICAL",
  "CONDUCT.",
  "WE",
  "CREATE",
  "STATE-OF-THE-ART",
  "LANDMARK",
  "BUILDINGS",
  "AND",
  "SUSTAINABLE",
  "INFRASTRUCTURE,",
  "DELIVERING",
  "INTEGRATED",
  "SERVICES",
  "FROM",
  "DESIGN",
  "TO",
  "CONSTRUCTION.",
  "[img2]",
  "OUR",
  "TAILORED",
  "APPROACH",
  "PRIORITIZES",
  "LIFE-CYCLE",
  "PERFORMANCE",
  "AND",
  "MAINTENANCE-FREE",
  "SOLUTIONS.",
  "[img3]",
];

export const ABOUT_STATS = [
  { value: 2006, label: "YEAR FOUNDED", suffix: "" },
  { value: 100, label: "COMPLETED PROJECTS", suffix: "+" },
  { value: 30, label: "ONGOING PROJECTS", suffix: "+" },
  { value: 15, label: "GOVERNMENT PROJECTS", suffix: "+" },
  { value: 100, label: "SATISFIED CLIENTS", suffix: "%" },
];

export const CLIENT_IMAGES = Array.from({ length: 18 }, (_, i) => `/images/clients/${i + 1}.png`);
